---
name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Mock Benchmark
        run: |
          echo "Mocking the benchmark"

      - name: Sleep for x seconds
        run: sleep 10
