---
name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  MAIN_BRANCH_NAME: main
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Mock image build
        run: |
          echo "Mocking the image builds"

      - name: Sleep for x seconds
        run: sleep 10
