---
name: e2e tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Mock e2e tests
        run: |
          echo "Mocking e2e tests"

      - name: Sleep for x seconds
        run: sleep 10
