name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Mock add issue to project
        run: |
          echo "Mocking e2e tests"

      - name: Sleep for x seconds
        run: sleep 10
