---
name: License Scan

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  fossa-scan:
    name: Find license compliance and security issues
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Mock license compliance and security issues
        run: |
          echo "Mocking license compliance and security issues"

      - name: Sleep for x seconds
        run: sleep 10
