---
name: Release crate

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version (no `v` prefix)"
        required: true
        default: "1.0.0"

jobs:
  build:
    name: Release create
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "version: ${{ inputs.version }}"

      - name: Sleep for x seconds
        run: sleep 10
